name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./aoc2022-01
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./aoc2022-01
      run: cargo test --verbose
    - name: Run application
      working-directory: ./aoc2022-01
      run: cargo run
